name: Binance Scanner

on:
  schedule:
    - cron: "3 0,4,8,12,16,20 * * *"   # TR saatiyle 03:03, 07:03, 11:03, 15:03, 19:03, 23:03
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install aiohttp pandas numpy
      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BINANCE_BASES: "https://data-api.binance.vision,https://api-gcp.binance.com,https://data.binance.com,https://api1.binance.com,https://api2.binance.com,https://api3.binance.com,https://api4.binance.com"
        run: python Tarabot4saat.py
